<center><h1>Лабораторна робота №2</h1>
    <h3>Студетна групи АнД - 31</h3>
    <h3>Білухи Назара Романовича</h3>
    <h3>Варіант 1</h3>
    <h3>TensorFlow</h3></center>


In [1]:
import tensorflow as tf

## Створення тензору 

In [3]:
# Незмінюваний тензор
tensor = tf.constant('Value')
tensor

<tf.Tensor: shape=(), dtype=string, numpy=b'Value'>

In [4]:
tensor = tf.constant([[1,0,1], [2,3,4]])
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 1],
       [2, 3, 4]])>

In [5]:
tensor = tf.constant([1,3,5,2,4,6], shape=(2,3))
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [6]:
# змінюваний тензор
tensor = tf.Variable([[1,2,3], [3,2,1]])
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 2, 1]])>

In [19]:
tensor[0].assign([0,0,0])
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 0, 0],
       [3, 2, 1]])>

## Створення набору даних для визначення властивостей

In [18]:
tensor = tf.math.round(tf.random.uniform((3, 3, 2, 2), -100, 100))
tensor

<tf.Tensor: shape=(3, 3, 2, 2), dtype=float32, numpy=
array([[[[ 65., -82.],
         [-59., -93.]],

        [[ 67.,  55.],
         [ 84., -90.]],

        [[-32., -29.],
         [-21., -42.]]],


       [[[ 76., -18.],
         [-36., -95.]],

        [[-29., -58.],
         [-83.,  63.]],

        [[ 82.,  64.],
         [-90., -71.]]],


       [[[-51., -39.],
         [ -0.,  68.]],

        [[ 13., -82.],
         [ 21., -18.]],

        [[  1.,  23.],
         [-27., -53.]]]], dtype=float32)>

In [27]:
# Властивості тензору
print('Тип елементів тензору:', tensor.dtype)
print('Вигляд(форма) тензору:', tensor.shape)
print('Порядок тензору:', tensor.ndim)
print('Розмір тензору:', tf.size(tensor).numpy())
print('Кількість елементів першої осі тензору:', tensor.shape[0])
print('Кількість елементів другої осі тензору:', tensor.shape[1])
print('Кількість елементів третьої осі тензору:', tensor.shape[2])
print('Кількість елементів четвертої осі тензору:', tensor.shape[3])

Тип елементів тензору: <dtype: 'float32'>
Вигляд(форма) тензору: (3, 3, 2, 2)
Порядок тензору: 4
Розмір тензору: 36
Кількість елементів першої осі тензору: 3
Кількість елементів другої осі тензору: 3
Кількість елементів третьої осі тензору: 2
Кількість елементів четвертої осі тензору: 2


## Базові операції

In [36]:
tf1 = tf.math.round(tf.random.uniform((3, 2, 2), -5, 5))
tf2 = tf.math.round(tf.random.uniform((3, 2, 2), -5, 5))
print('Перший тензор\n', tf1, '\n\nДругий тензор\n', tf2)

Перший тензор
 tf.Tensor(
[[[-3. -2.]
  [-2.  4.]]

 [[-3. -3.]
  [-4.  1.]]

 [[-3.  2.]
  [ 2.  3.]]], shape=(3, 2, 2), dtype=float32) 

Другий тензор
 tf.Tensor(
[[[ 4. -3.]
  [-4. -1.]]

 [[ 3.  0.]
  [ 1.  5.]]

 [[ 2. -3.]
  [-3.  5.]]], shape=(3, 2, 2), dtype=float32)


In [37]:
# додавання 
tf1 + tf2

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1., -5.],
        [-6.,  3.]],

       [[ 0., -3.],
        [-3.,  6.]],

       [[-1., -1.],
        [-1.,  8.]]], dtype=float32)>

In [38]:
# віднімання 
tf1 - tf2

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[-7.,  1.],
        [ 2.,  5.]],

       [[-6., -3.],
        [-5., -4.]],

       [[-5.,  5.],
        [ 5., -2.]]], dtype=float32)>

In [39]:
# множення на скаляр
tf1 * 3

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ -9.,  -6.],
        [ -6.,  12.]],

       [[ -9.,  -9.],
        [-12.,   3.]],

       [[ -9.,   6.],
        [  6.,   9.]]], dtype=float32)>

In [42]:
# множення матричне @ аналогічно tf.multiply
print(tf.multiply(tf1, tf2))
print('\n', tf1 @ tf2)

tf.Tensor(
[[[-12.   6.]
  [  8.  -4.]]

 [[ -9.  -0.]
  [ -4.   5.]]

 [[ -6.  -6.]
  [ -6.  15.]]], shape=(3, 2, 2), dtype=float32)

 tf.Tensor(
[[[ -4.  11.]
  [-24.   2.]]

 [[-12. -15.]
  [-11.   5.]]

 [[-12.  19.]
  [ -5.   9.]]], shape=(3, 2, 2), dtype=float32)


In [44]:
# векторне внутрішнє множення
tf.tensordot(tf1, tf2, axes=0)

<tf.Tensor: shape=(3, 2, 2, 3, 2, 2), dtype=float32, numpy=
array([[[[[[-12.,   9.],
           [ 12.,   3.]],

          [[ -9.,   0.],
           [ -3., -15.]],

          [[ -6.,   9.],
           [  9., -15.]]],


         [[[ -8.,   6.],
           [  8.,   2.]],

          [[ -6.,   0.],
           [ -2., -10.]],

          [[ -4.,   6.],
           [  6., -10.]]]],



        [[[[ -8.,   6.],
           [  8.,   2.]],

          [[ -6.,   0.],
           [ -2., -10.]],

          [[ -4.,   6.],
           [  6., -10.]]],


         [[[ 16., -12.],
           [-16.,  -4.]],

          [[ 12.,   0.],
           [  4.,  20.]],

          [[  8., -12.],
           [-12.,  20.]]]]],




       [[[[[-12.,   9.],
           [ 12.,   3.]],

          [[ -9.,   0.],
           [ -3., -15.]],

          [[ -6.,   9.],
           [  9., -15.]]],


         [[[-12.,   9.],
           [ 12.,   3.]],

          [[ -9.,   0.],
           [ -3., -15.]],

          [[ -6.,   9.],
           [  9

In [49]:
# інші операції
print("Середнє арифметичне:", tf.reduce_mean(tf1))
print("\nМаксимальний елемент по рядках:", tf.reduce_max(tf1))
print("\nМінмімальний елемент по рядках:", tf.reduce_min(tf1))
print("\nДобуток усіх елементів:", tf.reduce_prod(tf1))
print("\nКвадрат кожного елементу:\n", tf.square(tf1))

Середнє арифметичне: tf.Tensor(-0.6666667, shape=(), dtype=float32)

Максимальний елемент по рядках: tf.Tensor(4.0, shape=(), dtype=float32)

Мінмімальний елемент по рядках: tf.Tensor(-4.0, shape=(), dtype=float32)

Добуток усіх елементів: tf.Tensor(-62208.0, shape=(), dtype=float32)

Квадрат кожного елементу:
 tf.Tensor(
[[[ 9.  4.]
  [ 4. 16.]]

 [[ 9.  9.]
  [16.  1.]]

 [[ 9.  4.]
  [ 4.  9.]]], shape=(3, 2, 2), dtype=float32)
